layout: {zmk_keyboard: corne}
layers:
  Alphabets Layer:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: NONE, h: Function Layer}
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - RSHFT
  - {t: CAPS, h: LCTRL}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - RCTRL
  - LALT
  - {t: BSPC, h: Symbols Layer}
  - {t: ESC, h: Numeric Layer}
  - {t: RET, h: Navigation Layer}
  - SPACE
  - {t: DEL, h: RCMD}
  Numeric Layer:
  - {t: Bluetooth Layer, h: toggle}
  - ''
  - /
  - '*'
  - +
  - '-'
  - .
  - '7'
  - '8'
  - '9'
  - '*'
  - /
  - ''
  - ''
  - ''
  - ''
  - LSHFT
  - BSPC
  - '0'
  - '4'
  - '5'
  - '6'
  - +
  - RET
  - KP NUM
  - ''
  - ''
  - .
  - RET
  - ''
  - ''
  - '1'
  - '2'
  - '3'
  - '-'
  - BSPC
  - ''
  - ''
  - {type: held}
  - RCTRL
  - RALT
  - RCMD
  Symbols Layer:
  - '`'
  - '!'
  - '@'
  - '#'
  - $
  - '-'
  - '&'
  - '*'
  - (
  - )
  - ^
  - ''
  - ''
  - ''
  - ''
  - ''
  - LSHFT
  - BSPC
  - Q
  - ']'
  - '-'
  - '='
  - ''''
  - RET
  - ''
  - ''
  - ''
  - .
  - RET
  - ''
  - \
  - '['
  - '`'
  - W
  - E
  - BSPC
  - ''
  - {type: held}
  - ''
  - RCTRL
  - RALT
  - RCMD
  Navigation Layer:
  - ''
  - MUTE
  - VOL DN
  - VOL UP
  - BRI DN
  - BRI UP
  - PSCRN
  - ''
  - ''
  - ''
  - ''
  - {t: Bluetooth Layer, h: toggle}
  - ''
  - ''
  - HOME
  - ''
  - ''
  - BSPC
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  Function Layer:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F7
  - F8
  - F9
  - F10
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - LSHFT
  - ''
  - ''
  - F4
  - F5
  - F6
  - F11
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F1
  - F2
  - F3
  - F12
  - ''
  - LCMD
  - RALT
  - RCTRL
  - ''
  - ''
  - ''
  Bluetooth Layer:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&sys_reset'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&sys_reset'
  - {t: Alphabets Layer, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - {t: Alphabets Layer, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
